services:
  swutrack:
    build:
      dockerfile: ./service/Dockerfile
    environment:
      PORT: "8080"
      SHUTDOWN_TIMEOUT: "30s"
      POSTGRES_CONN_URL: "postgres://postgres:postgres@postgres:5432/swutrack?sslmode=disable"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: swutrack
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5